/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 hat.gltf --transform
Author: shedmon (https://sketchfab.com/shedmon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hats-040741c22c044da9bfc3fef06e48625e
Title: Hats
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Portfolio/hat-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.19, -0.97]} rotation={[-1.16, 0, 0]} scale={0.04}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Hat_1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Hat_2} />
      </group>
    </group>
  )
}

useGLTF.preload('/Portfolio/hat-transformed.glb')
