/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 workspace.gltf --transform
Author: SINNIK (https://sketchfab.com/sinnik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-gadgets-ab36d3ecad9d480c8d3232addb0caf03
Title: Modern Gadgets
*/

import React, { useEffect, useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import gsap from 'gsap'

export default function Model(props) {
  const mainref = useRef(null)
  const tl = useRef(null)
  const { nodes, materials } = useGLTF('/Portfolio/workspace-transformed.glb');
  useFrame(()=>{
    // if(mainref.current) {
    //   mainref.current.rotation.z = -20
    // }
    // console.log(mainref.current.rotation.z);

    if(window.scrollY < 400 && mainref.current.rotation.z < -0.15 ){
      if( mainref.current.rotation.z >= -0.15){
        mainref.current.rotation.z = -0.15
        return;
      }
      mainref.current.rotation.z += window.scrollY / 400
    }
 

    // if(mainref.current.rotation.z < -18.5){
    //   console.log(mainref.current);
    //   mainref.current.rotation.z += 0.01
    //   mainref.current.scale.z -= 0.001
    //   mainref.current.scale.x -= 0.001
    //   mainref.current.scale.y -= 0.001

    // }
  })

  // useEffect(()=>{
  //   if(mainref.current) {
  //     mainref.current.rotation.z = -20
  //   }
  // },[mainref.current])

  useLayoutEffect(()=>{
    tl.current = gsap.timeline()
    // tl.current.from(
    //   mainref.current.rotation,{
    //     duration: 0,
    //     z: -18
    //   }
    // )

    // mainref.current.rotation.z = -20.4
    
    //   tl.current.from(
    //   mainref.current.rotation,{
    //     duration: 20,
    //     z: -18
    //   }
    // )

     tl.current.to(
       mainref.current.rotation,{
         duration: 1.5,
         z: -1.5
       }
     )
   
  },[])

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} ref={mainref}>
        <mesh geometry={nodes.Object_2.geometry} material={nodes.Object_2.material} />
        <mesh geometry={nodes.Object_3.geometry} material={nodes.Object_3.material} />
        <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
        <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
        <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
        <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
        <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
        <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
        <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
        <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
        <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
        <mesh geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} />
        <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
        <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
        <mesh geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
        <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
        <mesh geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
        <mesh geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
        <mesh geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
        <mesh geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
        <mesh geometry={nodes.Object_22.geometry} material={nodes.Object_22.material} />
        <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
        <mesh geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} />
        <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
        <mesh geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
        <mesh geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
        <mesh geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
        <mesh geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
        <mesh geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
        <mesh geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
        <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
        <mesh geometry={nodes.Object_33.geometry} material={nodes.Object_33.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/Portfolio/workspace-transformed.glb')
